Repository Dauren-Delmukhambetov/cautious-giggle, pull requests merged in 2021-09, with the labels that each got.

#62 #44 Implement exception handling for REST API
  api/toko-rest-api.yaml
  src/main/java/kz/toko/app/controller/errors/GlobalExceptionHandler.java
  src/test/java/kz/toko/app/controller/ProductsIT.java
  src/test/java/kz/toko/app/controller/UsersIT.java
  src/test/resources/db.scripts/add_another_product_to_delete.sql
Labels: enhancement

#78 #74: Added deployment configuration file
  .github/workflows/gradle.yml
  build.gradle
Labels: infrastructure

#82 #72: Updating readme file and adding PR and issue templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  build.gradle
  src/main/java/kz/toko/app/service/impl/MinioFileStorageService.java
Labels: documentation

#89 #51: Introducing PMD plugin to check code style
  build.gradle
  src/main/java/kz/toko/app/event/ProductImageChangeEvent.java
  src/main/java/kz/toko/app/exception/EntityDeletedException.java
  src/main/java/kz/toko/app/exception/EntityNotFoundException.java
  src/main/java/kz/toko/app/service/impl/S3FileStorageService.java
Labels: enhancement

#91 #73: Authentication in Swagger UI
  .gitignore
  api/toko-rest-api.yaml
  build.gradle
  src/main/java/kz/toko/app/config/SecurityConfig.java
  src/main/java/kz/toko/app/service/impl/ProductServiceImpl.java
  src/main/java/kz/toko/app/service/impl/UserServiceImpl.java
  src/main/resources/application.yaml
  src/test/java/kz/toko/app/controller/UsersIT.java
Labels: enhancement
