Repository Dauren-Delmukhambetov/cautious-giggle, pull requests merged in 2021-08, with the labels that each got.

#36 #26 Implement user deletion
  api/toko-rest-api.yaml
  src/main/java/kz/toko/app/controller/UserController.java
  src/main/java/kz/toko/app/entity/AuditableEntity.java
  src/main/java/kz/toko/app/service/UserService.java
  src/main/java/kz/toko/app/service/impl/UserServiceImpl.java
  src/test/java/kz/toko/app/controller/UsersIT.java
  src/test/resources/db.scripts/add_one_user.sql
  src/test/resources/db.scripts/delete_all_users.sql
Labels: enhancement

#43 #42: Added delete method for products and some refactoring
  api/toko-rest-api.yaml
  docker-compose.it.yaml
  docker-compose.yaml
  src/main/java/kz/toko/app/controller/ProductController.java
  src/main/java/kz/toko/app/exception/EntityDeletedException.java
  src/main/java/kz/toko/app/repository/ProductRepository.java
  src/main/java/kz/toko/app/service/ProductService.java
  src/main/java/kz/toko/app/service/impl/ProductServiceImpl.java
  src/test/java/kz/toko/app/controller/ProductsIT.java
  src/test/resources/db.scripts/add_product_to_delete.sql
Labels: enhancement

#48 #45: Adding AWS S3 support
  build.gradle
  src/main/java/kz/toko/app/config/FileStorageConfig.java
  src/main/java/kz/toko/app/service/impl/MinioFileStorageService.java
  src/main/java/kz/toko/app/service/impl/S3FileStorageService.java
  src/main/resources/application-aws.yaml
  src/main/resources/application.yaml
Labels: enhancement

#54 Adding unit tests for ProductServiceImpl
  src/test/java/kz/toko/app/service/impl/ProductServiceImplTest.java
Labels: enhancement

#56 #46: Switching app to MySQL as RDBMS
  .github/workflows/gradle.yml
  .gitignore
  build.gradle
  docker-compose.it.yaml
  docker-compose.yaml
  src/main/resources/application-aws.yaml
  src/main/resources/application.yaml
  src/main/resources/db/migration/V202105141702__init.sql
  src/main/resources/db/migration/V202105292030__create_user.sql
  src/main/resources/db/migration/V202108101800__change_price_precision.sql
  src/test/resources/application-it.yaml
  src/test/resources/db.scripts/add_one_product.sql
  src/test/resources/db.scripts/add_one_user.sql
  src/test/resources/db.scripts/add_product_to_delete.sql
Labels: enhancement, infrastructure

#60 Disabled minio version upgrade via Renovate
  .github/renovate.json
Labels: dependencies

#67 #50: Adding JaCoCo plugin to evaluate code coverage rate
  build.gradle
Labels: infrastructure

#66 #65: Image auto-deletion mechanism
  build.gradle
  src/main/java/kz/toko/app/event/ProductImageChangeEvent.java
  src/main/java/kz/toko/app/event/listener/ProductEventListener.java
  src/main/java/kz/toko/app/repository/ProductRepository.java
  src/main/java/kz/toko/app/service/ProductService.java
  src/main/java/kz/toko/app/service/impl/MinioFileStorageService.java
  src/main/java/kz/toko/app/service/impl/ProductServiceImpl.java
  src/test/java/kz/toko/app/event/listener/ProductEventListenerIT.java
Labels: enhancement
