Repository Dauren-Delmukhambetov/cautious-giggle, pull requests merged in 2021-06, with the labels that each got.

#10 Configure CI workflow
  .github/workflows/gradle.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: infrastructure

#12 #8: Adding Product creation API implementation
  src/main/java/kz/toko/app/controller/ProductController.java
  src/main/java/kz/toko/app/entity/AuditableEntity.java
  src/main/java/kz/toko/app/entity/ProductEntity.java
  src/main/java/kz/toko/app/mapper/ProductMapper.java
  src/main/java/kz/toko/app/service/ProductService.java
  src/main/java/kz/toko/app/service/impl/ProductServiceImpl.java
Labels: enhancement

#14 #13: Added step to build image
  .github/workflows/gradle.yml
  README.md
  build.gradle
  settings.gradle
  src/main/resources/application.yaml
Labels: infrastructure

#27 Configure Renovate Bot
  .github/renovate.json
  renovate.json
Labels: dependencies

#11 #6 Implemented user creation flow
  api/toko-rest-api.yaml
  src/main/java/kz/toko/app/controller/UserController.java
  src/main/java/kz/toko/app/entity/AuditableEntity.java
  src/main/java/kz/toko/app/entity/UserEntity.java
  src/main/java/kz/toko/app/mapper/UserMapper.java
  src/main/java/kz/toko/app/repository/UserRepository.java
  src/main/java/kz/toko/app/service/UserService.java
  src/main/java/kz/toko/app/service/impl/UserServiceImpl.java
  src/main/resources/db/migration/V202105292030__create_user.sql
Labels: enhancement
